sonar.organization=pida1200
sonar.projectKey=pida1200_mujdum
sonar.projectName=mujdum

sonar.sources=backend/src,backend/scripts,frontend/src
sonar.tests=backend/test,frontend/test

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.db-merge-backup/**,**/coverage/**
sonar.coverage.exclusions=**/test/**,**/*.test.ts,**/*.test.tsx,frontend/src/main.tsx,frontend/src/ui/TestUiCharts.tsx,frontend/src/ui/App.tsx
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.typescript.tsconfigPaths=backend/tsconfig.json,frontend/tsconfig.json
